### ISSUE TITLE
Internal Server Error After Site Creation

### ISSUE THREAD

**Issue by alinaqvie** [frappe/helm#100]
I am using kubernetes cluster with docker.

I Successfully created site here is the logs.

Attempt 1 to connect to mariadb.default.svc.cluster.local:3306
Attempt 1 to connect to frappe-bench-erpnext-redis-queue:12000
Attempt 1 to connect to 10.103.190.138:6379
Attempt 1 to connect to frappe-bench-erpnext-redis-socketio:11000
Connections OK
Created user _3c3d3934fa5e49ca
Created database _3c3d3934fa5e49ca
Granted privileges to user _3c3d3934fa5e49ca and database _3c3d3934fa5e49ca
Starting database import...
Imported from database /home/frappe/frappe-bench/apps/frappe/frappe/database/mariadb/framework_mariadb.sql

Installing frappe...
Updating DocTypes for frappe        : [========================================] 100%
Updating country info               : [========================================] 100%

Installing erpnext...
Updating DocTypes for erpnext       : [========================================] 100%
Updating customizations for Address
Updating customizations for Contact
*** Scheduler is disabled ***

I access website outside. here is the error.

Internal Server Error

Why it show ??

I reinstall site manually  its work fine. here is the command.

bench --site test1.example.ae reinstall

This will wipe your database. Are you sure you want to reinstall? [y/N]: y
MySQL root password:

Installing frappe...
Updating DocTypes for frappe        : [========================================] 100%
Updating country info               : [========================================] 100%
Set Administrator password:
Re-enter Administrator password:

Installing erpnext...
Updating DocTypes for erpnext       : [========================================] 100%
Updating customizations for Address
Updating customizations for Contact
*** Scheduler is disabled ***

**Comment by revant** [comment]
re-open if needed
