### ISSUE TITLE
volumePermissions flag is broken

### ISSUE THREAD

**Issue by stevenbarragan** [frappe/helm#105]
## Description of the issue

Using the `volumePermissions.enabled=true` breaks `erpnext/templates/deployment-erpnext.yaml` [line 34](https://github.com/frappe/helm/blob/main/erpnext/templates/deployment-erpnext.yaml#L33) 

```bash
> helm template erpnext-pipe --namespace default frappe/erpnext --set mariadbHost=mari-mariadb.default.svc.cluster.local --set persistence.worker.storageClass=standard-
rwx --set persistence.logs.storageClass=standard-rwx --set volumePermissions.enabled=true

Error: YAML parse error on erpnext/templates/deployment-erpnext.yaml: error converting YAML to JSON: yaml: line 34: did not find expected key
helm.go:88: [debug] error converting YAML to JSON: yaml: line 34: did not find expected key
YAML parse error on erpnext/templates/deployment-erpnext.yaml
```

It breaks because the `securityContext` ends up like
```yml
      securityContext:
        {}
        capabilities:
          add: ["CAP_CHOWN"]
```

The solution would be to merge the result of
```
{{- toYaml .Values.securityContext | nindent 12 }}
```

with
```
capabilities:
  add: ["CAP_CHOWN"]
```

**Comment by revant** [comment]
Please send a PR it you've fixed it.

**Comment by stevenbarragan** [comment]
Do you know how to accomplish such thing?

**Comment by revant** [comment]
> `erpnext/templates/deployment-erpnext.yaml` [line 34](https://github.com/frappe/helm/blob/main/erpnext/templates/deployment-erpnext.yaml#L33)
>

fix the template here with the help of https://helm.sh/docs/chart_template_guide/control_structures/
You may have to try it locally using the local directory for helm chart. Try with `--dry-run` to check if the change works.

You will also have to update:

- values.yaml (for new config property)
- README.md of chart to describe the new values property which defaults to be backward compatible
