### ISSUE TITLE
CAP_CHOWN vs CHOWN

### ISSUE THREAD

**Issue by stevenbarragan** [frappe/helm#106]
What's the difference between `CAP_CHOWN` and `CHOWN` in [here](https://github.com/frappe/helm/blob/main/erpnext/templates/deployment-erpnext.yaml#L36)?

`CAP_CHOWN` gave me issues on gcloud. I changed to `CHOWN` and it worked just fine. I could send a PR to change this but I'm not sure about the effects on other platforms. should it be a configurable Value?

**Comment by revant** [comment]
No idea. It was added by a PR.

> I could send a PR to change this but I'm not sure about the effects on other platforms. should it be a configurable Value?

try to make it configurable and backward compatible with existing releases.

**Comment by revant** [comment]
securityContext will be configurable
