### ISSUE TITLE
Template for custom app nginx/worker images

### ISSUE THREAD

**Issue by joshuarestivo** [frappe/helm#111]
Following the docs in https://github.com/frappe/frappe_docker, I've created worker and nginx images for a custom app. Now, the helm chart needs to be made aware of these additional images. It looks like a deployment template needs to be created and the job* templates modified accordingly. 

Are there docs or examples available for inserting custom images like this?

**Comment by revant** [comment]
just override values for image repo and tag with your images. (this should solve your problem)

if you need to add deployments of your own then as this chart as a sub chart and build your own chart (this is not what you're looking for, this is for custom non frappe apps working with frappe.)

**Comment by revant** [comment]
open issue again if necessary.
