### ISSUE TITLE
Cannot create site due to the mistaken value in the template

### ISSUE THREAD

**Issue by GiuseppeCofano** [frappe/helm#115]
## Description of the issue

In the templates folder, the createSite feature is not working. The reason:

In the create site Job template, this line:

`{{- if and (.Values.createSite.enabled) (.Values.dbRootPassword) }}`

should actually be like this:

`{{- if and (.Values.createSite.enabled) (.Values.createSite.dbRootPassword) }}`

## Context information (for bug reports)
Trying to deploy Erpnext and create a site, not working

## Steps to reproduce the issue

1. Deploy with "createSite: enabled" as an input

### Observed result
The ingress is created but not the site. This is due to the fact that the create site Job template is not created, since the if at the beginning does not result true.

### Expected result
Both site and ingress created.

**Comment by revant** [comment]
please send a PR, I'll merge.

**Comment by revant** [comment]
the job now has been updated. re-open if needed.
