### ISSUE TITLE
v3.2.51-v3.2.52 Migration Job failes with OCI runtime exec: "/bin/bash": no such file or directory

### ISSUE THREAD

**Issue by timschneider** [frappe/helm#121]
It appeares to me that there is a breaking change in the erpnext-nginx image between version v13.22.0 and v13.22.1 in relation to /bin/bash and /bin/sh.

That is the reason why the migration job will stuck on that:
https://github.com/frappe/helm/blob/ea9782c2d76f23cf613923b4fd9f899e895c58ed/erpnext/templates/job-migrate-sites.yaml#L35-L37

![grafik](https://user-images.githubusercontent.com/2517553/161215138-2855950b-fb45-4e91-ae8a-956b8782f9c6.png)

The Docker Image v13.22.0 is using  CMD ["bash"]
https://hub.docker.com/layers/erpnext-nginx/frappe/erpnext-nginx/v13.22.0/images/sha256-2aea9bc0d6a5c97ad3270606270e44e08dfc312f6b315ce01d3a9c0a30d844ea?context=explore

and the Docker Image v13.22.1 is using CMD ["/bin/sh"]
https://hub.docker.com/layers/erpnext-nginx/frappe/erpnext-nginx/v13.22.1/images/sha256-56472fe59325580b889aa6e75112483cc621aa291bab2ca78a695841d06d057b?context=explore

but this change is not propergated into the helm charts v3.2.51-v3.2.52, so they are broken and should be disabled or removed or updated to a version working v3.2.53 version.

**Comment by revant** [comment]
can you send the fix if you identified it?

I'll send it this week.

**Comment by revant** [comment]
The chart versions are different and ERPNext versions are different.

When you wish to upgrade minor erpnext versions you need incrementally upgrade to docker image tags.

Helm chart versions are for the templates and resources that are created.

If you are on v4 and start with you can gradually migrate erpnext.

erpnext-3.2.51, erpnext-3.2.52, erpnext-4.0.0, erpnext-4.0.1 all are using ERPNext v13.22.1, so migrating to new helm charts will not skip any ERPNext upgrade.
