### ISSUE TITLE
mariadb service name fix

### ISSUE THREAD

**Issue by darren1713** [frappe/helm#122]
## Steps to reproduce the issue

1. Update mariadb config to architecture: replication
2. Mariadb node name is now [project]-mariadb-primary
3. Charts are hard coded as "-mariadb" with no options for overrides. Even dbHost doesn't allow override

### Example patch
https://github.com/darren1713/helm-erpnext/commit/1e2c93219360676f6dd9757abe50d98fab86a7dc

This patch is not the best way to go about this, but it does allow dbHost to be overridden by moving it to the first "if" statement. It would be best to auto-detect this as noted below.

The best resolution would be to add a check for mariadb / architecture == "replication" and appropriately set the DB_HOST environment variables to [project]-mariadb-primary (replication) or [project]-mariadb (standalone)

**Comment by revant** [comment]
> The best resolution would be to add a check for mariadb / architecture == "replication" and appropriately set the DB_HOST environment variables to [project]-mariadb-primary (replication) or [project]-mariadb (standalone)

can you send a PR please!

**Comment by darren1713** [comment]
Two updates are in this PR

- Update create site timeout to 10 minutes while waiting for the site json to be created. It was 2 minutes, which is not enough time for a redundant mariadb install and site configure to complete
- Resolve naming of -mariadb and -mariadb-primary automatically based on values.yaml

PR is here: https://github.com/frappe/helm/pull/123

**Comment by revant** [comment]
PR is merged, I'll make a release later today or tomorrow.

**Comment by revant** [comment]
https://helm.erpnext.com/erpnext-4.0.14.tgz
