### ISSUE TITLE
Upgrading: ERPNext image version selection

### ISSUE THREAD

**Issue by darren1713** [frappe/helm#124]
## Steps to reproduce

1. Install an older version: helm install ...... --version 4.0.11
2. Install a newer version: helm upgrade ..... --version 4.0.14
3. Image tag names/versions are not upgraded 

### Observed result
When upgrading to a new erpnext / helm version as shown above, the image versions are not updated

### Expected result
When deploying a chart (new or upgrade), the appropriate image tag versions should be managed in the chart for:
nginx: image: tag: vx.x.x
worker: image: tag: vx.x.x
socketio: image: tag: vx.x.x

I'm not familiar enough with the chart architecture / helm process to recommend the best course of action for this. Other charts we do deploy, such as mariadb, ingress-nginx, etc, manage the image versions within the chart.

In this use case, I would have expected that when upgrading the helm chart to v4.0.14 that the image tags would have upgraded to v13.28.0 as well.

**Comment by revant** [comment]
> helm upgrade ..... --version 4.0.14

can you share full upgrade command? Do you have additional `-f values.yaml` or `--set` params?
what is in values.yaml? if the values are overridden, do they contain image and tags hardcoded in custom values file?

**Comment by darren1713** [comment]
Thanks for having a look at that, completely my mistake. Closing this.
