### ISSUE TITLE
Helm chart updated erpnext but not frappe

### ISSUE THREAD

**Issue by extremegf** [frappe/helm#125]
Hello, I've updated the deployment using `helm upgrade --install` command. Erpnext version was bumped but frappe wasn't.

![Screenshot from 2022-05-26 16-42-49](https://user-images.githubusercontent.com/1788593/170512206-e1d517bf-4af4-4919-96e4-d74dc6a87c23.png)

Are there any other steps necessary?
Thank you!

**Comment by dj12djdjs** [comment]
This is because frappe didn't release an update. You can check the releases here:
https://github.com/frappe/frappe/releases

For erpnext:
https://github.com/frappe/erpnext/releases

**Comment by extremegf** [comment]
Oh, you're right. I didn't check that. Sorry for the trouble!
