### ISSUE TITLE
Support `ingressClassName` in ingress

### ISSUE THREAD

**Issue by ath88** [frappe/helm#128]
**Is your feature request related to a problem? Please describe.**
`ingressClassName` is required if you don't want your default ingress controller to serve for the defined service.

**Describe the solution you'd like**
It should be possible to configure the value of `spec.ingressClassName` in the ingress template.

**Comment by revant** [comment]
Can you send a PR if you are already using it.

**Comment by revant** [comment]
Wait for helm chart to be bumped automatically with next Frappe/ERPNext release.
