### ISSUE TITLE
ERPNext support in TrueCharts

### ISSUE THREAD

**Issue by Asteliks** [frappe/helm#141]
**Is your feature request related to a problem? Please describe.**
I like running my server programs as simple as it gets that is why I'm using TrueNAS SCALE. Yea I know that this perhaps is not a pro solution but it is simple and that is enough. In order to use ERPNext in TrueNAS SCALE with ease it would be great if you guys could add it to the TrueNAS SCALE apps catalog. One of such app Catalogs is [TrueCharts](https://github.com/truecharts/charts). I would recommend this catalog because it works especially well with traefik.

**Describe the solution you'd like**
Adding ERPNext to TrueCharts would enable me and other users to actually use ERPNext on TrueNAS SCALE systems.

**Additional context**

- Intro to [Using SCALE Apps](https://www.truenas.com/docs/scale/scaleuireference/apps/usingapps/);
- This has been requested at [TrueCharts github](https://github.com/truecharts/charts/issues/2435) however it is not a priority and may take longer to implement.

**Comment by Asteliks** [comment]
I understand your pain. I will try helm.erpnext.com

Unfortunately I have tried and failed miserably. I’m just not there yet when it comes to kubernetes and charts. That is why I have hoped for help from someone more experienced. I would want to undermine Erpnext quality due to my poor implementation of it in true charts.

**Comment by Asteliks** [comment]
A small update from my side: over this entire time, I've been trying to get ERPNext running via the mentioned Helm Chart in TrueNAS Scale but unfortunately to no avail. According to my research Helm Charts just do not work with TrueNAS Scale.

I've also tried creating a duplicate chart in the aforementioned [TrueCharts](https://github.com/truecharts/charts) but failed as well. I would seem I'm lacking some knowledge.

Could I ask you to give TrueCharts a try? From what I see the maintenance is fully automated ones a chart is created thus maintaining it will come with minimal effort.

**Comment by revant** [comment]
can you provide access to setup somewhere?

**Comment by Asteliks** [comment]
Currently I do not have other than LAN access to my setup. Truth be told as it contains some privet data. I would rather not change that. 
However, that should not be an issue because [TrueNAS SCALE](https://www.truenas.com/download-truenas-scale/) is open and 100% free. As such you can, without an issue, setup a VM of it. The only thing that I have changed is I have added [TrueCharts to my SCALE](https://truecharts.org/docs/manual/guides/Adding-TrueCharts). Other than that, my setup uses the default setting so that will not be a problem.

**Comment by Asteliks** [comment]
@revant do you see any chance of adding ERPNext to TrueCharts?

**Comment by revant** [comment]
I'm not adding and maintaining it. I don't even use whatever you're asking me to install.

if you are the only user here, you should add and maintain it

**Comment by Asteliks** [comment]
It would seem that you have closed this as complete where as you should have closed it as incomplete/ won’t be solved

**Comment by revant** [comment]
I'll keep it open only for you.
