### ISSUE TITLE
Support for Longhorn storage class

### ISSUE THREAD

**Issue by dberardo-com** [frappe/helm#144]
I have started installation of the chart changing the storageClass value, but containers won't start because they try to mount using nfs 

MountVolume.MountDevice failed for volume "pvc-83dddb10-75e7-4d0b-acc0-ebd6c647fb88" : rpc error: code = Internal desc = mount failed: exit status 32 Mounting command: /usr/local/sbin/nsmounter Mounting arguments: mount -t nfs -o vers=4.1,noresvport,intr,hard 10.43.104.121:/pvc-83dddb10-75e7-4d0b-acc0-ebd6c647fb88 /var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/bde3903ef273b2e80424ad6c201f8e838b186b6db189ae96bc05c2ac389174a8/globalmount Output: mount: wrong fs type, bad option, bad superblock on 10.43.104.121:/pvc-83dddb10-75e7-4d0b-acc0-ebd6c647fb88, missing codepage or helper program, or other error (for several filesystems (e.g. nfs, cifs) you might need a /sbin/mount.<type> helper program) In some cases useful info is found in syslog - try dmesg | tail or so.

**Comment by revant** [comment]
You need to configure your cluster to get the storage class working. Getting a working cluster with loadbalancer, storage class, networking is out of scope of this repo.

For nfs errors in general: Make sure you have nfs-utils or nfs-common installed on your nodes.

I've used storage class that allow RWX access mode.

- [Rook/cephfs](https://rook.io/docs/rook/latest-release/Getting-Started/quickstart)
- [nfs-ganesha-server-and-external-provisioner](https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner)
- [nfs-subdir-external-provisioner](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner)
- [AWS EFS CSI](https://docs.aws.amazon.com/eks/latest/userguide/efs-csi.html)

All of them worked without any tweaks.

As long as the storage class allows RWX access mode it will work. If it doesn't allow RWX it is not going to work for ERPNext. So no point in even expecting enhancement.

For people who are building serverless api using frappe framework and don't wish to have RWX, they can mount `ConfigMap` for `/home/frappe/frappe-bench/sites/common_site_config.json` and `/home/frappe/frappe-bench/sites/{site-name}/site_config.json` and it will start the gunicorn/worker/websocket service and connect to backing services through configmap mounted json. Rest of the state will be dropped. e.g. attached public/private files won't be stored.  Build frappe API that stores files to object storage if required. Custom api can be made stateless to be used as function or run on HA cluster.

**Comment by dberardo-com** [comment]
ok, UPDATE: i have managed to understand what went wrong. apparently longhorn requires nfs-utils to be installed on the host machines for RWX to be enabled: https://v1-2-1--longhornio.netlify.app/docs/1.2.1/advanced-resources/rwx-workloads/

but now i still get some errors and pods dont come up, it seems that no "site" is existing in the gunicorn pod, since nginx shows "localhost is not defined". 

is there any working default configuration for the helm chart to start a default environment with a initial site  ?

**Comment by revant** [comment]
run the bench configuration job again, it'll create the required config file and apps.txt

**Comment by revant** [comment]
Closing as longhorn storage class was fixed by installing packages needed for nfs. Issue suggested ERPNext helm chart doesn't support longhorn storage class.

> For nfs errors in general: Make sure you have nfs-utils or nfs-common installed on your nodes.

For apps.txt or common_site_config.json make sure the nfs vol has correct permissions and ownership for files.

create conf job again to re configure apps.txt and common_site_config.json.

Create new issue.
