### ISSUE TITLE
v6.0.0 chart ignores image names

### ISSUE THREAD

**Issue by cwooldridge** [frappe/helm#151]
Version 6.0.0 of the helm chart seems to ignore config values for custom images.
Version 5.0.58 seems to work correctly.

Upgrading to v6.0.0 caused only erpnext v14.12.1 images to be pulled.

**Comment by revant** [comment]
> Upgrading to v6.0.0 caused only erpnext v14.12.1 images to be pulled.

there's only one image to pull now.
there was a pr waiting for 2 weeks stating that there will be only one image. That pr was merged.

I'll fix the nginx config part,

make sure it's not a template, it needs to be a exact config file to be overriden.

**Comment by revant** [comment]
I verified,

the config override works as expected.

1. now the config is mounted as `/etc/nginx/conf.d/default.conf` directly.
2. it must NOT contain env vars. Ther is NO template + env var -> config.

**Comment by cwooldridge** [comment]
Thank you. I will adjust my build.  I must of have missed the PR.

**Comment by JamiuEjiwumi** [comment]
> I verified.
> 
> The config override works as expected.
> 
> 1. now the config is mounted as `/etc/nginx/conf.d/default.conf` directly.
> 2. it must NOT contain env vars. There is NO template + env var -> config.

@revant, I am currently having issues with installing my custom-app on erpnext. 
1. erpnext is already deployed on my kubernetes cluster and it's running, I also create a new site and the UI is up.
2. I have been able to built the images for worker and ngix and is on ghcr.io/****/worker:latest and ghcr.io/****/nginx:latest.
3. I need help on how to install the custom application on the running erpnext on the cluster, which file or files do I need to modify?

Thanks in anticipation of your help

**Comment by guinanlin** [comment]
> 3\. I need help on how to install the custom application on the running erpnext on the cluster, which file or files do I need to modify?

looking forward to reply. I have the same issue about add custom application  into the running erpnext cluster.
how to modify the custom yaml?

**Comment by revant** [comment]
- Run the configure bench job https://github.com/frappe/helm/blob/main/erpnext/templates/job-configure-bench.yaml. It creates apps.txt from the list of apps available after image is updated.
- Either run custom job to `bench --site {site_name} install-app {app_name}` https://github.com/frappe/helm/blob/main/erpnext/templates/job-configure-bench.yaml or exec into any of the frappe-bench container and exec the command `bench --site {site_name} install-app {app_name}`
- Make sure apps.txt has the entry of app before install-app is executed.

**Comment by guinanlin** [comment]
> 
tks for your reply. following your suggestions, I try to make a custom job, after running job, it give me the error.

`apiVersion: batch/v1
kind: Job
metadata:
  name: erpnext-install
spec:
  template:
    metadata:
      name: erpnext-install
    spec:
      containers:
      - name: erpnext-install
        image: frappe/erpnext:v14.17.2
        command: ["/bin/bash", "-c", "bench get-app https://gitee.com/yuzelin/erpnext_chinese.git && bench --site erp.dty install-app erpnext_chinese"]
      restartPolicy: Never`

**Comment by revant** [comment]
You cannot execute bench get-app in production containers

https://github.com/frappe/frappe_docker/wiki/Frequently-Asked-Questions#how-to-install-official-or-custom-apps
