### ISSUE TITLE
How to restore backups

### ISSUE THREAD

**Issue by paulator** [frappe/helm#178]
Hi, 

I want to migrate to ERPNext v14 in a Kubernetes-Cluster. My current production environment is on plain docker containers running v13.

I read the documentation for ERPNext Kubernetes / Helm setup and I found, how to create a backup. But I found no information, how to restore a backup. My backup is on google drive and I want to restore the backup on the Kubernetes environment.

Can you give me a hint, how to do that?

All the best
--thomas

**Comment by revant** [comment]
use `kubectl cp`

Or check this if it helps https://gist.github.com/revant/2414cedce8e19d209d5d337ea19efabc
