### ISSUE TITLE
Creation of MariaDB User with wrong rights

### ISSUE THREAD

**Issue by DrZoidberg09** [frappe/helm#180]
I dont know if it really belongs to the Helm Chart, but it seems to be pretty much Kubernetes related.

If I create a new site or restore a DB, there will be a new database created along with the DB User. However, this user is restricted to the IP of the pod that initiated the process.

Hence, when another worker pod is accessing the DB, there will be an access denied error.

So far I manually corrected it to '%'@_database after the creation of the user. But I think there could be a better way? :)

**Comment by revant** [comment]
When you create the new site use `--no-mariadb-socket` parameter. Example: `bench new-site --no-mariadb-socket ...` it will create user with wildcard as host

**Comment by MichaelMcCulloch** [comment]
Sir, this is a helm chart.
