### ISSUE TITLE
Error /bin/sh: 1: ../env/bin/python: not found when execute bench --site command migrate before starting the custom app

### ISSUE THREAD

**Issue by dungtc** [frappe/helm#183]
## Description of the issue
Build custom app and start to run `bench --site my_site migrate` before running the image I got this error

Reason: because the WORKDIR is **"/home/frappe/frappe-bench"** and the bench bin_path was configured with absolute path **"../env/bin"** in https://github.com/frappe/frappe/blob/develop/frappe/commands/utils.py#L565C15-L565C16 

The requirement path must be **"/home/frappe/frappe-bench/sites"**

### Expected result
Change the WORKDIR of custom app from **"/home/frappe/frappe-bench"** to **"/home/frappe/frappe-bench/sites"** to run bench commands before starting the app

### Stacktrace / full error message if available
Run `bench --site my_site migrate` before starting the custom app
```
"/bin/sh: 1: ../env/bin/python: not found"
```

**Comment by revant** [comment]
Make sure you use correct apps.json

https://github.com/frappe/frappe_docker/blob/main/docs/custom-apps.md
