### ISSUE TITLE
PDF printing documents "Get PDF"

### ISSUE THREAD

**Issue by not-Ryan** [frappe/helm#195]
## Description of the issue
Print of documents gets a weird layout and `get pdf` at the top.

## Context information (for bug reports)
[Code that prints it?](https://github.com/search?q=repo%3Afrappe%2Ffrappe+download_pdf&type=code)

The HTML from public works splendidly.
However when I print (with pdfprint) it fails like so.

- I tried `bench build` but that just breaks everything.
- I tried copying assets from `/usr/shared/nginx` but that doesn't exist.
- I tried redeploying.

## Steps to reproduce the issue
1. Deploy helm with custom_app built image on v15.4.1.
2. Restore backup from old site.
3. Create a quotation or any document.
4. Email or print that document

### Observed result
![Screenshot 2023-12-07 at 12-11-56 SAL-QTN-2023-00001 pdf](https://github.com/frappe/helm/assets/22834199/a613d8bf-6a7a-4f9f-9604-4d0f20758e84)

### Expected result
![Screenshot 2023-12-07 at 12-14-03 Master Annick Smithers - SAL-QTN-2023-00001](https://github.com/frappe/helm/assets/22834199/5de63998-8ed1-4e23-ba26-012ac60929a9)

**Comment by revant** [comment]
adding `"host_name": "https://erp.site.com"` to `site_config.json` solved it for me. In my case site name and host header is same.
