### ISSUE TITLE
Add option to use CA certificates for secure MySQl DB connections

### ISSUE THREAD

**Issue by nikolaybobkov91** [frappe/helm#197]
**Is your feature request related to a problem? Please describe.**
At this moment it`s not possible to connect to DBs (currecntly testing TiDB serverless) which require usage of CA certificates (secure connections).
During the executions pods fail with smth like that type of error:
_pymysql.err.OperationalError: (1105, 'Connections using insecure transport are prohibited. See https://docs.pingcap.com/tidbcloud/secure-connections-to-serverless-tier-clusters')_ 

**Describe the solution you'd like**
Could you please add parameters lower to helm chart configuration values?
db_ssl_ca
db_ssl_cert
db_ssl_key
https://frappeframework.com/docs/user/en/basics/site_config

**Describe alternatives you've considered**

**Additional context**

**Comment by revant** [comment]
Send a pull request please.

**Comment by revant** [comment]
If you don't mind keeping the certs in "sites" volume then just run `bench --site .. set-config db_ssl_ca /home/frappe/frappe-bench/sites/site.name.com/...pem`.

If you need to mount them as secrets then you need to send PR to allow all deployments to mount additional volumes and use additional secrets from in values.yaml
