### ISSUE TITLE
Error: getaddrinfo ENOTFOUND frappe-redis-socketio-master

### ISSUE THREAD

**Issue by khaledtahaQ** [frappe/helm#198]
i installed frappe-erpnext on my cluster using helm chart, everything works fine except socket.io, I'm getting this exception..
![image](https://github.com/frappe/helm/assets/118350686/2ce51f64-15c4-4180-a8b1-95be69a424aa)

**Comment by revant** [comment]
`frappe-redis-socketio-master` service must be up and running. Check if the redis pods are running?

**Comment by khaledtahaQ** [comment]
@revant the idea that there is no svc with name frappe-redis-socketio-master, all pods are running 
![image](https://github.com/frappe/helm/assets/118350686/c37223a9-fa43-485c-be9f-04d1faf15fa2)
svc :
![image](https://github.com/frappe/helm/assets/118350686/ba69ba34-a4ee-48aa-8810-a889599f8bd0)

**Comment by revant** [comment]
Set redis_socketio to point to redis-queue. There is no more separate redis for socketio

**Comment by khaledtahaQ** [comment]
@revant how i can do that using helm ?

**Comment by revant** [comment]
pull latest helm chart and run configure bench job

**Comment by khaledtahaQ** [comment]
@revant   i did it many times but nothing changed

**Comment by revant** [comment]
Then you need to manually edit the common_site_config.json and remove socketio_redis

Or set it to point to redis queue master

**Comment by khaledtahaQ** [comment]
@revant it's empty. is there another method?

**Comment by revant** [comment]
> @revant it's empty. is there another method?

common_site_config.json should have appropriate values after conf-bench job completes. Check pod log for conf-bench pod.
