### ISSUE TITLE
How to setup ngnix and siteconfig for filesize through helm?

### ISSUE THREAD

**Issue by albseb511** [frappe/helm#200]
I am not able to setup the max Size on siteconfigs on the pods and ngnix which is part of helm.
How do i override this and do it through the config file itself?

**Comment by revant** [comment]
there are multiple nginx involved.

For internal nginx:

- use `nginx.envVars` in values.yaml to pass `CLIENT_MAX_BODY_SIZE`.
- or use `nginx.config` override in values.yaml to override the complete nginx config with custom one.

For ingress-nginx use https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#custom-max-body-size

**Comment by albseb511** [comment]
yea i think this seems to be working. thanks.
