### ISSUE TITLE
the chart should provide an extra volumes field.

### ISSUE THREAD

**Issue by migs35323** [frappe/helm#202]
**Is your feature request related to a problem? Please describe.**

there are several issues with the chart including broken css from a broken linking between the different containers/pods. (made an issue in erpnext main repo because its not only on kubernetes other users reported the issue on docker as well)

however today i went to install an extra app, i did try it as a custom job, then i did install it in a running pod.
Some pods started to crash because the lack of `~/frappe-bench/apps/$APP` in it's filesystem (it's present on the pod i did install but not the others, like the scheduller)
So now i need to manually patch every single deployment to add a new pvc with the installed app

**Describe the solution you'd like**
I'd like to request an extra volumes field so we can add an extra pvc (or more, or even re-use the rwx sites volume) 
and place installed apps in this pvc.
maybe i can even place the frappe and erpnext apps on it directly and solve the css mismatch issue...

**Additional context**

**Comment by migs35323** [comment]
update:
it seems that there is a underlying issue that prevents the solution that i suggested, when mapping the pvc using the subpath
example:

```
  - mountPath: /home/frappe/frappe-bench/apps/persona
    name: extra-apps
    subPath: persona
```

when trying to install the app, bench tries to issue a rmdir which fails...

**Comment by revant** [comment]
Additional volume is fine 

Additional volume for apps will make the container mutable. Then you need frappe-bench/env common as well. It is not a good idea.

Any other volumes for any other locations is great. Will help as secrets for this #197
