### ISSUE TITLE
Backup Job as a `CronJob`

### ISSUE THREAD

**Issue by arsanysamuel** [frappe/helm#209]
I know there's a job for backing up the DB that is disabled by default.
As far as I can understand enabling this job will result in creating a backup every deployment, right?

Wouldn't it make more sense to convert that to a cron job? Or does frappe has a scheduled functionality by default?

**Comment by revant** [comment]
Backup strategy can be different.

For small setups simple job with `bench --site all backup --with-files` is enough. Then push those files to s3.

For medium setup you can go with `bench --site all backup` and then use s3 to snapshot `sites` directory which includes the db dump as well as files.

For large setups NFS volume snapshots and mariabackup snapshots makes more sense.

If you are okay above 3 levels, create a cronjob for your use. If using kubernetes, you can even use other projects like velero to take backups.
