### ISSUE TITLE
additional volume mount

### ISSUE THREAD

**Issue by fzhan** [frappe/helm#217]
Is there a way to add volume mount through value.yaml? I'm trying to install hrms through commands but every time it restarts, the apps folder will reset from the image. With extraVM will resolve this issue.

**Comment by revant** [comment]
Don't use Kubernetes please. Docker-compose I can understand, even frappecloud is using podman as a VM. Use something like that. Or search forum for non kubernetes installs. For kubernetes you need to have immutable image custom built with all additional apps.

https://github.com/frappe/frappe_docker/wiki/Frequently-Asked-Questions#how-to-install-official-or-custom-apps

**Comment by revant** [comment]
For anyone looking for Volumes in values for other things, do send a PR.

**Comment by fzhan** [comment]
@revant sorry for my limited understanding. I thought helm is meant to be used with k8s.

I've managed to mount additional volumes via customised yaml, might be a good idea to include in the future.
