### ISSUE TITLE
volumeMount prevent changes made to assets folder

### ISSUE THREAD

**Issue by fzhan** [frappe/helm#218]
## Description of the issue
Current helm package mounts "sites" folder, however, the assets folder does not get override. So when additional apps are added, the assets cannot be found

## Context information (for bug reports)
Try to install other apps like hrms and visit the site, assets will report missing.

**Comment by revant** [comment]
Have you built hrms custom image? 

I don't have any issue with my image https://gitlab.com/castlecraft/cepl-erpnext-images/container_registry/3822033

If you're not building the custom image please close the issue
https://github.com/frappe/helm/issues/217#issuecomment-2412913984
