### ISSUE TITLE
templating for the erpnext PVC access mode

### ISSUE THREAD

**Issue by ajmaltridz** [frappe/helm#219]
**Is your feature request related to a problem? Please describe.**
Currently, the PVC access mode is fixed and can't be modified via the values file. This limits flexibility in environments like single-node clusters or test setups where RWX isn't needed, requiring a fork to adjust access modes

**Describe the solution you'd like**
I can send a PR if its possible

**Describe alternatives you've considered**

**Additional context**

**Comment by revant** [comment]
> I can send a PR if its possible

Yes! send! once merged it'll be available after next release cycle (release happens one or two times a week)
