### ISSUE TITLE
Add tracing

### ISSUE THREAD

**Issue by blaggacao** [frappe/helm#24]
I might do that myself one day, for reference:

https://medium.com/opentracing/take-opentracing-for-a-hotrod-ride-f6e3141f7941

A good showcase.

Ref:
- https://w3c.github.io/trace-context/
- https://www.jaegertracing.io/docs/1.17/sampling/#adaptive-sampler

**Comment by Thunderbottom** [comment]
I think it is better to leave it to the people to add what they require and instead just provide with a decent base on our end. We can surely do better in terms of improving the installation process before looking at other things. So that should be our priority right now, I would say.

**Comment by blaggacao** [comment]
I just made some experiments to it, and it looks like it would need eventually a tracing support within the framework itself, so it might be more involved than I thought, initially, still it might be worth pursuing low prio.

**Comment by revant** [comment]
#### deployment-erpnext (erpnext-nginx + erpnext-worker pod) :

- It has frontend client - Incoming requests from users on port 80 
- serves assets.
- reverse proxy gunicorn on port 8000 (same pod)
- reverse proxy socketio service on 9000 (external service)

#### frappe-socketio service:
- it is nodejs/socketio on port 9000

As a monolith, communication is not much distributed in ERPNext.

```
nginx+worker > frappe socketio
```

Just to separate the pods/service it is represented like this.
App point of view it is same whole thing.

I haven't checked, I think config tells python app to make internal http requests on socketio:9000.
It is used to pass message from python app that needs to show up on subscribed browser websocket.

There not much http requests going on internally to serve user request.

**Comment by blaggacao** [comment]
+ probably interactions with redis instances

**Comment by revant** [comment]
I'll close this for now as it needs to be part of framework and ERPNext first
