### ISSUE TITLE
problem with restore-backups 

### ISSUE THREAD

**Issue by mashkovd** [frappe/helm#29]
Hello,

1. I [Create Push Backup S3 Secret ](https://helm.erpnext.com/kubernetes-resources/create-push-backup-s3-secret).
2. After [Create Backup Sites Job](https://helm.erpnext.com/kubernetes-resources/create-backup-sites-job)
3. Then [Backups to Cloud](https://helm.erpnext.com/kubernetes-resources/create-push-backups-to-cloud-job)
and then i try [Restore Backups from Cloud](https://helm.erpnext.com/kubernetes-resources/create-restore-backups-job) I have next error - 
`
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/commands/restore_backup.py", line 187, in <module>
    main()
  File "/home/frappe/frappe-bench/commands/restore_backup.py", line 148, in main
    pull_backup_from_s3()
  File "/home/frappe/frappe-bench/commands/restore_backup.py", line 134, in pull_backup_from_s3
    for obj in bucket.objects.filter(Prefix=bucket_dir):
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/boto3/resources/collection.py", line 83, in __iter__
    for page in self.pages():
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/boto3/resources/collection.py", line 166, in pages
    for page in pages:
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/botocore/paginate.py", line 255, in __iter__
    response = self._make_request(current_kwargs)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/botocore/paginate.py", line 332, in _make_request
    return self._method(**current_kwargs)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/botocore/client.py", line 626, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the ListObjects operation: The specified key does not exist.`

Can you help me what I do wrong?
Thanks!

I see my backup on S3 like 
Amazon S3/frappe/frappe/backups/test.example.ru/20200520_005432

**Comment by revant** [comment]
Can you share your yamls?

**Comment by revant** [comment]
I've faced an error like this once, when I manually tried to 
create backup directory structure on s3 and tried to restore.

Creating backup folder structure first
Then uploading files one by one in bucket caused error during restore.

Push backup directly creates file locations.

Manually adding folders creates folder structure along with files.

Example,

Manual case created following structure/objects,

bucket-dir/
bucket-dir/site.com/
bucket-dir/site.com/timestamp/
bucket-dir/site.com/timestamp/db.sql.gz
bucket-dir/site.com/timestamp/private-files.tar
bucket-dir/site.com/timestamp/public-files.tar

push-backup command creates following structure/objects,

bucket-dir/site.com/timestamp/db.sql.gz
bucket-dir/site.com/timestamp/private-files.tar
bucket-dir/site.com/timestamp/public-files.tar

restore-backup command doesn't handle blank directory structure. Loop through first three items of manual case throws error.

**Comment by mashkovd** [comment]
> Can you share your yamls?

[s3-secret.txt](https://github.com/frappe/helm/files/4656191/s3-secret.txt)
[backup-sites.txt](https://github.com/frappe/helm/files/4656199/backup-sites.txt)
[push-backups.txt](https://github.com/frappe/helm/files/4656200/push-backups.txt)
[restore-backups.txt](https://github.com/frappe/helm/files/4656232/restore-backups.txt)

I don't use manually created backup yet. 
When i do job _backup-sites_ and _push-backups_ i see follow directory on S3
![image](https://user-images.githubusercontent.com/1842423/82436899-34879600-9a9f-11ea-86e7-c506fa9d1d68.png)
and after _restore-backups_ job get **error**

I use image - frappe/erpnext-worker:v11, may be problem in it

**Comment by revant** [comment]
Why is there double nesting?

```
[bucket-name] > [bucket-name] > [bucket-dir] > [site-name] > [timestamp]
```

It should be 

```
[bucket-name] > [bucket-dir] > [site-name] > [timestamp]
```

try changing endpoint url to? "http://s3.amazonaws.com"

https://docs.aws.amazon.com/general/latest/gr/s3.html

Note: Not related, I think it is recommended to use https

**Comment by mashkovd** [comment]
It's my mistake. I use wrong ENDPOINT_URL. Thanks for [url](https://docs.aws.amazon.com/general/latest/gr/s3.html)!
I use firstly)

And yet. How do better restore from my local site (for example, _site1.local_) to new site test.stteam.ru
I try now to upload **renamed archive** of site _site1.local_ to test.stteam.ru. I think it'not good practise and have follow message now:
![image](https://user-images.githubusercontent.com/1842423/82491382-4001ae00-9aed-11ea-8b79-69458cc7e80b.png)

What's next step. Sorry if i ask many...

**Comment by revant** [comment]
First try clearing cookies / application cache for the site on browser

If it doesn't work, try running migration job using v11 image.

rename > backup > push > restore should work for restoring local site.

**Comment by mashkovd** [comment]
> rename > backup > push > restore should work for restoring local site.
Explain me, pls...

I do backup site1.local  , after rename archive and upload to s3 and try restore from S3. It's right way?
Now try migrate my old site...

**Comment by revant** [comment]
> I do backup site1.local , after rename archive and upload to s3 and try restore from S3. It's right way?
> Now try migrate my old site...

ssh into vps

```
git clone frappe_docker

cd frappe-bench

# symlink commands which run in docker-bench in native frappe-bench
ln -s ~/frappe_docker/build/common/commands ~/frappe-bench/commands

# activate frappe-bench python environment
. ./env/bin/activate

# change to sites directory
cd sites

# rename site
mv site1.local test.example.ru 

# run backup command
WITH_FILES=1 python ../commands/backup.py

# set required env variables
export BUCKET_NAME=bucket-name
export BUCKET_DIR=my-backups
export ACCESS_KEY_ID=access_key
export SECRET_ACCESS_KEY=secret_key
export ENDPOINT_URL=https://cloud.url
export REGION=s3-region

# run push backup command
python ../commands/push_backup.py
```

**Comment by mashkovd** [comment]
It's great instruction!
Thanks! It's work perfectly...

**Comment by revant** [comment]
Documented Instructions here

https://github.com/frappe/frappe_docker/wiki/Migrate-from-frappe-bench-to-containerized-cloud

**Comment by mashkovd** [comment]
hi
now, i have message in log 
```
touch: cannot touch '/var/www/html/sites/.build': No such file or directory
```
Do you have this error when restore backup? thanks

**Comment by revant** [comment]
At core, the backup works like it runs in the frappe_docker/tests.

https://github.com/frappe/frappe_docker/blob/develop/tests/docker-test.sh

```shell
...
echo -e "\e[1m\e[4mPush backup to MinIO s3\e[0m"
docker run \
    -e BUCKET_NAME=erpnext \
    -e REGION=us-east-1 \
    -e BUCKET_DIR=local \
    -e ACCESS_KEY_ID=$MINIO_ACCESS_KEY \
    -e SECRET_ACCESS_KEY=$MINIO_SECRET_KEY \
    -e ENDPOINT_URL=http://minio:9000 \
    -v frappebench00_sites-vol:/home/frappe/frappe-bench/sites \
    --network frappebench00_default \
    frappe/erpnext-worker:edge push-backup
echo -e "\n"

...

echo -e "\e[1m\e[4mRestore backup from MinIO / S3\e[0m"
docker run \
    -e MYSQL_ROOT_PASSWORD=admin \
    -e BUCKET_NAME=erpnext \
    -e BUCKET_DIR=local \
    -e ACCESS_KEY_ID=$MINIO_ACCESS_KEY \
    -e SECRET_ACCESS_KEY=$MINIO_SECRET_KEY \
    -e ENDPOINT_URL=http://minio:9000 \
    -e REGION=us-east-1 \
    -v frappebench00_sites-vol:/home/frappe/frappe-bench/sites \
    --network frappebench00_default \
    frappe/erpnext-worker:edge restore-backup
echo -e "\n"
```

https://github.com/frappe/frappe_docker/blob/develop/tests/docker-test.sh

If you're using old image, you may have to pull latest image or build your own image.

There was a fix related to push and restore https://github.com/frappe/frappe_docker/pull/363

**Comment by revant** [comment]
re-open if needed
