### ISSUE TITLE
Can not create new site

### ISSUE THREAD

**Issue by cneumaier** [frappe/helm#33]
## Description of the issue
I am not able to create a new site via a job.

## Context information (for bug reports)
Kubernetes cluster v1.18.0, erpnext helm chart v1.0.3
## Steps to reproduce the issue

1. fresh helm install
2. creating site job 

### Observed result
the job fails and the site is not created.

### Expected result
Job should succeed and site should be created.

### Stacktrace / full error message if available
```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/commands/new.py", line 84, in <module>
    main()
  File "/home/frappe/frappe-bench/commands/new.py", line 49, in main
    reinstall=False,
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py", line 67, in _new_site
    make_site_dirs()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/installer.py", line 267, in make_site_dirs
    os.makedirs(dir_path)
  File "/opt/bitnami/python/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/opt/bitnami/python/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/opt/bitnami/python/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: './erp.example.com'
```

**Comment by revant** [comment]
Following must exist
1. mariadb-root-password secret must exist https://helm.erpnext.com/kubernetes-resources/create-mariadb-root-password-secret
2. mariabd secret must be in erpnext namespace

**Comment by revant** [comment]
Initially I thought It is about mariadb. Sorry for that.

I'm using this chart in production on kubernetes v1.18.2. I'm not able to recreate the issue.

Is PVC correct? can you create a pod and attach the same pvc and check if it is accessible by uid 1000?

**Comment by cneumaier** [comment]
@revant the database seems not to be the issue. I will try your purposed steps for the pvc and report back. 
Thanks for the help so far!

**Comment by revant** [comment]
Re-open if needed.

**Comment by evanf** [comment]
Hi @revant 
I have the same problem when creating a new site via a job.
I create a busybox pod with `spec.securityContext.runAsUser: 1000`  and attach the same pvc, run command `ls -al` in path `/home/frappe/frappe-bench/sites`, and get result below:
```
/home/frappe/frappe-bench/sites $ ls -al
total 13
drwxr-xr-x    3 root     root          4096 Feb  2 03:07 .
drwxr-xr-x    3 root     root          4096 Feb  2 04:57 ..
-rw-r--r--    1 root     root             0 Jan  3 16:35 .build
-rw-r--r--    1 root     root            15 Feb  2 03:06 apps.txt
drwxr-xr-x    2 root     root          4096 Feb  2 03:07 assets
-rw-r--r--    1 1000     1000           339 Feb  2 03:07 common_site_config.json
```
It seems the pvc is mounted as `root`.

The PVC I used in "create new site job" is created by Helm charts installation.
