### ISSUE TITLE
API for app

### ISSUE THREAD

**Issue by mashkovd** [frappe/helm#41]
Hi,
Can you help me with following thing?

I need get all site name from current app, for example.
It's need API or something else?
Thanks!

**Comment by revant** [comment]
Following command will list contents of `sites` directory.

```
kubectl exec -it -n <namespace> <helm-frappe-bench-release>-erpnext-erpnext-xxxxxxxxx-xxxxx -c erpnext-python -- ls
```

**Comment by mashkovd** [comment]
Works well, thank you!
