### ISSUE TITLE
How to upgrade to v13 beta

### ISSUE THREAD

**Issue by deantheiceman** [frappe/helm#46]
I'd like to upgrade my deployment to v13 beta, is it possible with this helm chart?

**Comment by revant** [comment]
Set the image tag while installing/upgrading helm chart release.

https://helm.erpnext.com/faq.html#how-do-i-customize-values-for-the-erpnext-helm-chart

**Comment by deantheiceman** [comment]
Is there anything else that needs to be done to upgrade other then change the image tag?

Thanks

**Comment by revant** [comment]
https://helm.erpnext.com/faq.html#how-do-i-upgrade-and-migrate-to-the-latest-helm-release

- set the MariaDB host and storageClass.
- set the additional tags
- set migrateJob.enable
