### ISSUE TITLE
add new site job failed

### ISSUE THREAD

**Issue by govindsmenokee** [frappe/helm#47]
While executing add new site job it is failing with the error 
`touch: cannot touch '/var/www/html/sites/.build': No such file or directory`

**Comment by revant** [comment]
@sunhoww

**Comment by revant** [comment]
Note: all tests are passing.

https://travis-ci.com/github/frappe/frappe_docker/jobs/361716218

**Comment by govindsmenokee** [comment]
@revant I followed  the instructions at k8resources.
The section - create new site. Find it using following command
`$ kubectl get deployments.apps -n <namespace> <helm-release-name>-erpnext-erpnext -o jsonpath="{.spec.template.spec.containers[0].image}"`
Gave a different image name I hade to use index 1 instead of 0 in the above command. Seems like a silly mistake from my end but the docs could be updated so that anyone who is setting this up first time doesn't face such issues.

You can close this issue. Thank you

**Comment by cpdeethree** [comment]
> @revant I followed the instructions at k8resources.
> The section - create new site. Find it using following command
> `$ kubectl get deployments.apps -n <namespace> <helm-release-name>-erpnext-erpnext -o jsonpath="{.spec.template.spec.containers[0].image}"`
> Gave a different image name I hade to use index 1 instead of 0 in the above command. Seems like a silly mistake from my end but the docs could be updated so that anyone who is setting this up first time doesn't face such issues.
> 
> You can close this issue. Thank you

This was my issue as well. For reference, the correct value in my case was frappe/erpnext-worker:v13.7.0 instead of frappe/erpnext-nginx:v13.7.0

When i changed index value from 0 to 1 it yielded correct value
