### ISSUE TITLE
How to run aribtary bench commands?

### ISSUE THREAD

**Issue by deantheiceman** [frappe/helm#53]
How do I run arbitary bench commands using the kubernetes method:

ie.

```
bench get-app --branch master tailpos-sync https://github.com/bailabs/tailpos-sync.git
bench --site jeeves install-app tailpos_sync
```

**Comment by revant** [comment]
Custom apps can't be installed on the fly, they already need to be in python environment 
https://github.com/frappe/helm/issues/50#issuecomment-663346353

>     bench --site jeeves install-app tailpos_sync

for installing existing apps from the image on to a site you can use frappe bench helper commands

https://github.com/frappe/frappe_docker/blob/develop/docs/site-operations.md#frappe-internal-commands-using-bench-helper

**Comment by deantheiceman** [comment]
Bench doesn't seem to be available on the image, how do I get it?

**Comment by revant** [comment]
Bench won't be available in production images.
