### ISSUE TITLE
workers environment variable

### ISSUE THREAD

**Issue by premkanish** [frappe/helm#54]
In the `common/worker/docker_entrypoint.sh` , there is a line:

```
if [[ -z "$WORKERS" ]]; then
    export WORKERS=2
 fi
```

**and** 

`if [[ -z "$RUN_AS_ROOT" ]]; then`

I am using helm chart and confused what these options are doing and where to set them.

**Comment by revant** [comment]
These are not exposed in helm charts anywhere.

You can set them while using single bench docker.

**Comment by revant** [comment]
Run as root not recommended on kubernetes node.

Scaling workers should be done by scaling pods for a distributed scale.

Both options make sense when not running on kubernetes.

I'll re-open issue if necessary.
