### ISSUE TITLE
Scaling out the scheduler 

### ISSUE THREAD

**Issue by zapsos** [frappe/helm#56]
In the docs section under what can be scaled out : 

It is unsure whether scheduler can be scaled out. It is set to replica: 1 by default.

As a learning curve i want to understand why we cant scale it when we can scale out the workers. Since i am taking this as my practical concept building i matched the contents of yaml for worker-d, worker-l and worker-s and found the scheduler chart is somewhat similar. Further more they both call the args which run the imported function from frappe.

Thanks!

**Comment by revant** [comment]
Try scaling it and check what happens!?

I think it will trigger jobs on scheduled intervals as many times as number of schedulers.

If there are 5 scheduler pods, the single scheduled job may get triggered 5 times.
