### ISSUE TITLE
Add an option to deploy mariadb alongside the curren setup

### ISSUE THREAD

**Issue by Niggl1999** [frappe/helm#71]
**Is your feature request related to a problem? Please describe.**
The chart doesn't has no option for a "builtin" database.
I know setting up another mariadb deployment isn't that hard but it's a quality of life/dev matter.
Personally I think a helmchart should supply you with everything you need to use the tool/whatever.

**Describe the solution you'd like**
The option to provision a mariadb deployment alongside the other erpnext deployments.
Most other charts I've used had a "builtin database" option or sth simmilar that was set to true by default.

**Describe alternatives you've considered**
Well I don't think there are any real alternatives, but I'm open for suggestions.

**Additional context**
The pain point was: I wanted to try erpnext -> I saw the helmchart -> I deployed the helmchart -> I missed the db was missing (and the pods weren't too happy about that).
Stuff like this can easily keep people from trying out (and maybe deciding to use) this project.

**Comment by revant** [comment]
https://github.com/frappe/helm/pull/66

This pr helps in creating your own "umbrella chart" with other charts.

I'll prefer not to use any databases on kubernetes. I don't use any stateful app on kubernetes.

**Comment by revant** [comment]
Even for DB there are 2 alternatives in helm chart, galera or master-slave

What about NFS Server provisioner chart? It's a deprecated chart.

If it is a must for you, do send a PR keeping things backward compatible.

I'll not prefer adding deprecated dependencies.

**Comment by revant** [comment]
What I found out 6 months ago

- We need RAM for hosting virtual storage. 4GB recommended for nodes that host cephfs/openebs
- For galera or mariadb charts, they need to be tweaked for reliability in production. (failovers, backups, restores) I think this requires skilled DBA who knows k8s + db on your team.
- I know db on k8s is possible, MariaDB SkySQL features show it uses k8s.

If anyone else has findings do post them.
