### ISSUE TITLE
Installation fails using Flux CD

### ISSUE THREAD

**Issue by Jimmy-Newtron** [frappe/helm#91]
We cannot use the helm chart into the Flux CD framework as described in the following issue

https://github.com/fluxcd/flux2/issues/1556#issue-928853437

The root cause looks to be the following line

https://github.com/frappe/helm/blob/c27ba7d38687a9a67331ab555e369b16c79685b5/erpnext/templates/serviceaccount.yaml#L15

Can you provide an helm chart without labels duplicate ?

Thanks in advance

**Comment by revant** [comment]
> Can you provide an helm chart without labels duplicate ?

You can send PR for changes you expect. I had used fluxcd last month

In fact the ERPNext feature board project is using FluxCD helm operator. Let me check again.

**Comment by Jimmy-Newtron** [comment]
As you can find in the issue opened in Flux, I have the problem only with the latest Flux version released these week
The Flux community have upgraded Helm

**Comment by revant** [comment]
Can you test the helm chart from my github fork/branch?

**Comment by Jimmy-Newtron** [comment]
**I have tested and it deploy everything smoothly**

The only point to remark is the failing test pod

![image](https://user-images.githubusercontent.com/24460646/123265146-0757b380-d4fb-11eb-9237-1357c58fd7d0.png)

I think it is due to some initial startup delay

**Comment by revant** [comment]
I'll publish a release in some time
