### ISSUE TITLE
Frappe Site State Terminated Reason Completed Exit Code: 0 Kubernetes Cluster

### ISSUE THREAD

**Issue by LinuxCloudMentor** [frappe/helm#98]
Hello,

We installed ERPNEXT with helm. we using separate Redis Cache and Mariadb on same namespace default in kubernetes.
Created New site status is Completed. Kindly see the attachment of logs and describes.

**Comment by revant** [comment]
logs are missing?

**Comment by revant** [comment]
the site did get created.

what's the problem you're facing after that?

**Comment by alinaqvie** [comment]
Here are the creating site logs.

kubectl logs new-app--1-ckb6p
Attempt 1 to connect to 10.100.38.235:3306
Attempt 1 to connect to frappe-bench-erpnext-redis-queue:12000
Attempt 1 to connect to 10.103.223.139:6379
Attempt 1 to connect to frappe-bench-erpnext-redis-socketio:11000
Connections OK
Created user _42204342a4907426
Created database _42204342a4907426
Granted privileges to user _42204342a4907426 and database _42204342a4907426
Starting database import...
Imported from database /home/frappe/frappe-bench/apps/frappe/frappe/database/mariadb/framework_mariadb.sql

Installing frappe...
Updating DocTypes for frappe        : [========================================] 100%
Updating country info               : [========================================] 100%
*** Scheduler is disabled ***

NAME                                                  READY   STATUS      RESTARTS      AGE
frappe-bench-erpnext-erpnext-86bb58688c-c9262         2/2     Running     1 (13m ago)   14m
frappe-bench-erpnext-redis-queue-5fd5f4465f-v2fgb     1/1     Running     0             14m
frappe-bench-erpnext-redis-socketio-646c795b9-qc4t6   1/1     Running     0             14m
frappe-bench-erpnext-scheduler-548f998948-9pw6q       1/1     Running     0             14m
frappe-bench-erpnext-socketio-764bcfdff9-9752p        1/1     Running     0             14m
frappe-bench-erpnext-worker-d-5fdb997cdf-dxfzc        1/1     Running     0             14m
frappe-bench-erpnext-worker-l-96875fdf4-n2622         1/1     Running     0             14m
frappe-bench-erpnext-worker-s-844dd57b74-kr22h        1/1     Running     0             14m
ingress-nginx-controller-5cc57bf6c7-p4v2h             1/1     Running     3 (12h ago)   3d
my-release-mariadb-0                                  1/1     Running     2 (12h ago)   16h
new-app--1-ckb6p                                      0/1     Completed   0             9m45s
nfs-client-provisioner-6bf54b8c9b-4qk62               1/1     Running     5 (29m ago)   2d23h
redis                                                 1/1     Running     4 (29m ago)   47h



Name:         new-app--1-ckb6p
Namespace:    default
Priority:     0
Node:         k8s-worker02/192.168.1.17
Start Time:   Fri, 08 Oct 2021 09:34:20 +0500
Labels:       controller-uid=d6c133df-d7ba-4f60-9783-37f25a10153d
              job-name=new-app
Annotations:  cni.projectcalico.org/containerID: d79b250959a6da57262e23a8ceb0454403853390f2c11813294cb526bcd70546
              cni.projectcalico.org/podIP:
              cni.projectcalico.org/podIPs:
Status:       Succeeded
IP:           192.168.69.198
IPs:
  IP:           192.168.69.198
Controlled By:  Job/new-app
Containers:
  create-site:
    Container ID:  docker://ace1624e9e42fb8eafea597aa71ff5dbe9a6e1013bf6a8653c758d377a5e1e56
    Image:         frappe/erpnext-worker:v13
    Image ID:      docker-pullable://frappe/erpnext-worker@sha256:739ed74c221c24de828fc8d8d2be478402222de51b64a0925048f4be162f0ab5
    Port:          <none>
    Host Port:     <none>
    Args:
      new
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Fri, 08 Oct 2021 09:34:35 +0500
      Finished:     Fri, 08 Oct 2021 09:42:09 +0500
    Ready:          False
    Restart Count:  0
    Environment:
      SITE_NAME:            new-app
      DB_ROOT_USER:         root
      MYSQL_ROOT_PASSWORD:  <set to the key 'mariadb-root-password' in secret 'my-release-mariadb'>  Optional: false
      ADMIN_PASSWORD:       ${ADMIN_PASSWORD}
    Mounts:
      /home/frappe/frappe-bench/sites from sites-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-cpgnz (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  sites-dir:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  frappe-bench-erpnext
    ReadOnly:   false
  kube-api-access-cpgnz:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  10m   default-scheduler  Successfully assigned default/new-app--1-ckb6p to k8s-worker02
  Normal  Pulled     10m   kubelet            Container image "frappe/erpnext-worker:v13" already present on machine
  Normal  Created    10m   kubelet            Created container create-site
  Normal  Started    10m   kubelet            Started container create-site

**Comment by alinaqvie** [comment]
> the site did get created.
> 
> what's the problem you're facing after that?
> 
> after creating the site, you'll need to create ingress.

root@k8s-master01:~# kubectl get ingress minimal-ingress
NAME              CLASS    HOSTS   ADDRESS   PORTS   AGE
minimal-ingress   <none>   *                 80      12s
root@k8s-master01:~# kubectl describe ingress minimal-ingress
Name:             minimal-ingress
Namespace:        default
Address:
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
Rules:
  Host        Path  Backends
  ----        ----  --------
  *
              /   frappe-bench-erpnext:80 (192.168.79.102:80)
Annotations:  nginx.ingress.kubernetes.io/rewrite-target: /
Events:       <none>

**Comment by alinaqvie** [comment]
I am stuck in Default backend

Name:             ingress-new-site
Namespace:        default
Address:
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
TLS:
  tls.new.app terminates new.app
Rules:
  Host        Path  Backends
  ----        ----  --------
  *
              /   frappe-bench-erpnext:80 (192.168.79.102:80)
Annotations:  cert-manager.io/cluster-issuer: letsencrypt-prod
              kubernetes.io/ingress.class: nginx
              kubernetes.io/tls-acme: true
Events:
  Type    Reason             Age   From                      Message
  ----    ------             ----  ----                      -------
  Normal  Sync               24s   nginx-ingress-controller  Scheduled for sync
  Normal  CreateCertificate  24s   cert-manager              Successfully created Certificate "tls.new.app"

**Comment by revant** [comment]
check the available services

`kubectl get svc -n <replace namespace>`

DO NOT COPY, change `<replace namespace>` to namespace where ERPNext helm release is installed.

the default backend should be `frappe-bench-erpnext`
